# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6bf97e76c3609f9955080c846324d471831594338f5b728769c10035f323939ca46fcc669947e4435f0bbab2ad4d4e83ca475d0437f5552c046c56cd3c378d6d

test:
  secret_key_base: 55c2c406534ba05a12f9729b41c13a13de0486788efbcf812e63eafe64a1ff188e3e5cfcc978c5f2c73f3ba70e4abd45cbe06d2d5552c20bf42e281957778dcd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
